server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # A mágica que impede o Erro 404 nas rotas do React:
        try_files $uri $uri/ /index.html;
    }
}